Fixed KeyError in importer.py. This issue occurred during the import of Vulnerability Templates
